import { Task } from '../types/todo';

const today = new Date().toISOString().split('T')[0];
const overdueDate = new Date(Date.now() - 86400000 * 2).toISOString().split('T')[0]; // 2 days ago

export const INITIAL_SAMPLE_TASKS: Task[] = [
  {
    id: 'task-sample-overdue',
    title: 'Submit Database lab report & ER diagrams',
    completed: false,
    status: 'in-progress',
    priority: 'high',
    dueDate: overdueDate,
    category: 'Study',
    estimatedMinutes: 45,
    pomodorosCompleted: 1,
    notes: 'Upload PDF to university portal. Ensure 3NF schema diagrams are attached.',
    subtasks: [
      { id: 'sub-od-1', title: 'Export PDF from Lucidchart', completed: true },
      { id: 'sub-od-2', title: 'Verify normalization explanations', completed: false },
    ],
    createdAt: new Date(Date.now() - 3600000 * 72).toISOString(),
  },
  {
    id: 'task-sample-today',
    title: 'Complete DSA assignment on Binary Search Trees',
    completed: false,
    status: 'in-progress',
    priority: 'high',
    dueDate: today, // Due Today!
    category: 'Study',
    estimatedMinutes: 60,
    pomodorosCompleted: 1,
    notes: 'Reference Chapter 7 in Cormen book. Implement insert, delete, and in-order traversal with tests.',
    subtasks: [
      { id: 'sub-1', title: 'Implement Node struct and insertion logic', completed: true },
      { id: 'sub-2', title: 'Write node deletion with 3 case handling', completed: false },
      { id: 'sub-3', title: 'Add test cases for edge boundary conditions', completed: false },
    ],
    createdAt: new Date(Date.now() - 3600000 * 24).toISOString(),
  },
  {
    id: 'task-sample-shopping',
    title: 'Buy fresh groceries & weekly meal prep ingredients',
    completed: false,
    status: 'todo',
    priority: 'medium',
    dueDate: new Date(Date.now() + 86400000 * 1).toISOString().split('T')[0],
    category: 'Shopping',
    estimatedMinutes: 30,
    notes: 'Pick up Greek yogurt, oats, chia seeds, spinach, and fresh fruits.',
    subtasks: [
      { id: 'sub-shop-1', title: 'Greek yogurt & oat milk', completed: true },
      { id: 'sub-shop-2', title: 'Chia seeds & raw almonds', completed: false },
      { id: 'sub-shop-3', title: 'Fresh blueberries & bananas', completed: false },
    ],
    createdAt: new Date(Date.now() - 3600000 * 14).toISOString(),
  },
  {
    id: 'task-sample-3',
    title: 'Build Portfolio project showcase page',
    completed: false,
    status: 'in-progress',
    priority: 'medium',
    dueDate: new Date(Date.now() + 86400000 * 5).toISOString().split('T')[0],
    category: 'Work',
    estimatedMinutes: 90,
    pomodorosCompleted: 0,
    notes: 'Include live demo URLs, GitHub repository links, and tech stack tags.',
    subtasks: [
      { id: 'sub-6', title: 'Design layout wireframe in Figma', completed: true },
      { id: 'sub-7', title: 'Write responsive CSS grid container', completed: false },
      { id: 'sub-8', title: 'Deploy on Vercel or GitHub Pages', completed: false },
    ],
    createdAt: new Date(Date.now() - 3600000 * 10).toISOString(),
  },
  {
    id: 'task-sample-health',
    title: 'Morning 5km jog & hydration routine',
    completed: true,
    status: 'completed',
    priority: 'medium',
    dueDate: today,
    category: 'Health',
    estimatedMinutes: 35,
    notes: 'Target pace under 5:45 min/km. Hydrate with electrolyte water.',
    createdAt: new Date(Date.now() - 3600000 * 8).toISOString(),
    completedAt: new Date(Date.now() - 3600000 * 1).toISOString(),
  },
  {
    id: 'task-sample-4',
    title: 'Review weekly budget & personal finance goals',
    completed: false,
    status: 'todo',
    priority: 'low',
    dueDate: new Date(Date.now() + 86400000 * 7).toISOString().split('T')[0],
    category: 'Personal',
    estimatedMinutes: 20,
    notes: 'Log recent utility bills and balance savings contributions.',
    createdAt: new Date(Date.now() - 3600000 * 4).toISOString(),
  },
];
